Models/Category.cs
using System.ComponentModel.DataAnnotations;
using ToDoList.Models.Enum;

namespace ToDoList.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public IList<ToDo> ToDos { get; set; } = new List<ToDo>();
    }
}

Models/Enum/CategoryType.cs
namespace ToDoList.Models.Enum
{
    public enum CategoryType
    {
        Work,
        Personal,
        Study,
        FamilyAndFriends
    }
}


//did not use this enum 

Models/Enum/Priority.cs
namespace ToDoList.Models.Enum
{
    public enum Priority
    {
        High, Medium , Low
    }
}

Models/ErrorViewModel.cs
namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ToDo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ToDoList.Models.Enum;

namespace ToDoList.Models
{
    public class ToDo
    {
        [Key]
        public int Id { get; set; }
        [Required (ErrorMessage ="Cant be empty")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Can not be Empty")]

        public string Description { get; set; }
        [Required(ErrorMessage = "can not be empty")]

        public Priority Priority { get; set; }

        [Required (ErrorMessage = "You Should choose")]
        public DateTime Deadline { get; set; }

        public bool IsFinshed { get; set; } = false;
        [ForeignKey("CategoryId")]

        public Category? Category { get; set; } // so it can just take the fk only and the obj can be null 
        public int CategoryId { get; set; }

        //constractor 


    }



}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoList.Context;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            //get category with the task 
            var categories = _context.Categories
                .Include(c => c.ToDos)
                .ToList();

            return View(categories);
        }



        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }



        // delete category 
        public IActionResult DeleteDirect(int id)
        {
            var category = _context.Categories
                .Include(c => c.ToDos)
                .FirstOrDefault(c => c.Id == id);

            if (category != null)
            {
                // delete all tasks with that spefic category
                _context.ToDos.RemoveRange(category.ToDos);

                // delete the category now after deleteing it tasks 
                _context.Categories.Remove(category);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }




    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToDoList.Context;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class ToDoController : Controller
    {

        private ApplicationDbContext _context; //it help us to deal with db create delete update 
        public ToDoController(ApplicationDbContext context) 
        {
            _context = context;
        }


        public IActionResult Create(int CategoryId) // it should match router 
        {
            if (CategoryId == 0)
            {
                return RedirectToAction("Index", "Category"); //if user have no categoryid retun it back to category user should add cetgory first 
            }

            var task = new ToDo { CategoryId = CategoryId }; // create ob then return it to view 
            return View(task);
        }

        [HttpPost]
        public IActionResult Create(ToDo task)
        {
            if (task.CategoryId == 0)
            {
                ModelState.AddModelError("CategoryId", "Please select a category");
            }

            if (ModelState.IsValid) // if eveything working 
            {
                _context.ToDos.Add(task);
                _context.SaveChanges();
                return RedirectToAction("Index", "Category");
            }

            return View(task); //return to add task page 
        }

        // is completed  
        public IActionResult ToggleStatus(int id)
        {
            var task = _context.ToDos.Find(id);
            if (task == null)
            {
                return NotFound();
            }

            // change if completed or not 
            task.IsFinshed = !task.IsFinshed;
            _context.SaveChanges();


            return RedirectToAction("Index", "Category");
        }

        // dispaly update page 
        public IActionResult Edit(int id)
        {
            var task = _context.ToDos.Find(id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // update 
        [HttpPost]
        public IActionResult Edit(ToDo task)
        {
            if (ModelState.IsValid)
            {
                _context.ToDos.Update(task);
                _context.SaveChanges();
                return RedirectToAction("Index", "Category");
            }

            return View(task);
        }

        // dispaly delete page 
        public IActionResult Delete(int id)
        {
            var task = _context.ToDos.Find(id);
            if (task == null)
            {
                return NotFound(); // do you want to delete 
            }

            return View(task);
        }

        // delete 
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var task = _context.ToDos.Find(id);
            if (task != null)
            {
                _context.ToDos.Remove(task);
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Category");
        }

    }
}

Views/Category/Create.cshtml
@model ToDoList.Models.Category

<h2>Add Category</h2>

<form asp-action="Create" method="post">
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>
    <button type="submit">Create</button>
</form>

Views/Category/Index.cshtml
@model List<ToDoList.Models.Category>

<h2>All Categories</h2>
<a asp-action="Create">+ Add Category</a> <!--Add category-->

@foreach (var cat in Model)
{
    <div style="border: 1px solid gray; margin:10px; padding:10px;">
        <div style="display: flex; justify-content: space-between;">
            <h3>@cat.Name</h3>
            <!--Delete category-->

            <a asp-controller="Category" asp-action="DeleteDirect" asp-route-id="@cat.Id"
               style="color: red; text-decoration: none;"
               onclick="return confirm('are you sure you want to delete? ');">
                ✕
            </a>
        </div>

        <!--add new category-->
        <a asp-controller="ToDo" asp-action="Create" asp-route-CategoryId="@cat.Id">
            + Add Task
        </a>
        <ul>
            @foreach (var task in cat.ToDos)
            {
                <li style="margin-bottom: 10px; @(task.IsFinshed ? "text-decoration: line-through;" : "")">
                    <span>@task.Name - @task.Deadline.ToShortDateString()</span> 

                    <!-- }controll butons -->
                    <div style="display: inline-block; margin-left: 10px;">
                        <!-- Done/not) -->
                        <a asp-controller="ToDo" asp-action="ToggleStatus" asp-route-id="@task.Id"
                           style="margin-right: 5px; text-decoration: none; color: @(task.IsFinshed ? "green" : "orange");">
                            @(task.IsFinshed ? "✓" : "○")
                        </a>

                        <!-- update-->
                        <a asp-controller="ToDo" asp-action="Edit" asp-route-id="@task.Id"
                           style="margin-right: 5px; text-decoration: none; color: blue;">
                            ✎
                        </a>

                        <!-- delete -->
                        <a asp-controller="ToDo" asp-action="Delete" asp-route-id="@task.Id"
                           style="text-decoration: none; color: red;">
                            ✕
                        </a>
                    </div>
                </li>
            }
        </ul>
    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/ToDo/Create.cshtml
@model ToDoList.Models.ToDo

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial"); 
    }
}

@if (ViewBag.ErrorMessage != null)
{
    <div style="color:red;">
        @ViewBag.ErrorMessage
    </div>
}

<h2>Add Task</h2>

<form asp-action="Create" method="post">
    <input type="hidden" asp-for="CategoryId" />


    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Priority"></label>
        <select asp-for="Priority" asp-items="Html.GetEnumSelectList<ToDoList.Models.Enum.Priority>()" class="form-control"> <!--Enum-->
            <option value="">-- Select Priority --</option>
        </select>
        <span asp-validation-for="Priority" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Deadline"></label>
        <input asp-for="Deadline" type="datetime-local" 
               value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")"
               class="form-control" />  <!--Timebox-->
        <span asp-validation-for="Deadline" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Add Task</button>
</form>

Views/ToDo/Delete.cshtml
@model ToDoList.Models.ToDo

<h2>Delete Task</h2>

<div class="alert alert-danger">
    <h3>Are you sure you want to delete this task?</h3>

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <button type="submit">Delete</button>
        <a asp-controller="Category" asp-action="Index" >Cancel</a>
    </form>
</div>

Views/ToDo/Edit.cshtml
@model ToDoList.Models.ToDo

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<h2>Edit Task</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="CategoryId" />

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Priority"></label>
        <select asp-for="Priority" asp-items="Html.GetEnumSelectList<ToDoList.Models.Enum.Priority>()" class="form-control">
            <option value="">-- Select Priority --</option>
        </select>
        <span asp-validation-for="Priority" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Deadline"></label>
        <input asp-for="Deadline" type="datetime-local" class="form-control" />
        <span asp-validation-for="Deadline" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>
            <input asp-for="IsFinshed" type="checkbox" />
            Task Completed
        </label>
    </div>

    <button type="submit">Save Changes</button>
    <a asp-controller="Category" asp-action="Index">Cancel</a>
</form>

Views/ToDo/Index.cshtml
@model List<ToDoList.Models.ToDo>

@{
    ViewData["Title"] = "Tasks List";
}

<h1>Tasks By Category</h1>
<h2>All Tasks</h2>
<hr />